import { useState } from 'react'
import { FileText, Shield, X, AlertTriangle } from 'lucide-react'
import FeedbackButton from './FeedbackButton'

const TERMS_TEXT = `Terms of Service

Last updated: 2026

1. Acceptance of Terms
By using Snap-to-Quiz, you agree to these terms. If you do not agree, please do not use the service.

2. Service Description
Snap-to-Quiz converts photos of lecture notes and textbooks into quizzes and flashcards using AI technology.

3. AI Accuracy
Content generated by Snap-to-Quiz is powered by artificial intelligence and may contain inaccuracies. You are responsible for verifying all information before relying on it.

4. User Accounts
You are responsible for maintaining the security of your account and password.

5. Acceptable Use
You agree not to misuse the service, including uploading copyrighted material you do not have rights to, or attempting to circumvent usage limits.

6. Payments
Pro subscriptions are processed securely via Paystack. Refunds are subject to our refund policy.

7. Limitation of Liability
Snap-to-Quiz is provided "as is" without warranties of any kind. We are not liable for damages arising from the use of our service.

8. Changes to Terms
We may update these terms periodically. Continued use constitutes acceptance of updated terms.`

const PRIVACY_TEXT = `Privacy Policy

Last updated: 2026

1. Information We Collect
We collect your email address and account credentials when you sign up. We store your generated study sets so you can access them later.

2. How We Use Your Information
We use your information to provide and improve the Snap-to-Quiz service, including managing your account, credits, and saved study materials.

3. Data Storage
Your data is stored securely using Supabase with row-level security. Only you can access your own data.

4. AI Processing
Photos you upload are sent to Google Gemini API for processing. We do not store the images themselves on our servers.

5. Third-Party Services
We use Supabase (database/auth), Google Gemini (AI), and Paystack (payments). Each has their own privacy practices.

6. Your Rights
You can request deletion of your account and associated data at any time.

7. Cookies
We use local storage to maintain your session and preferences. We do not use third-party tracking cookies.

8. Contact
For privacy concerns, please contact us through the app.`

function LegalModal({ title, content, onClose }) {
  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4"
      onClick={onClose}
    >
      <div
        className="bg-white rounded-2xl max-w-2xl w-full max-h-[80vh] overflow-hidden flex flex-col shadow-2xl animate-scale-in"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-200">
          <h3 className="text-lg font-semibold text-slate-900">{title}</h3>
          <button
            onClick={onClose}
            className="p-2 rounded-lg hover:bg-slate-100 transition-colors text-slate-500 hover:text-slate-700"
            aria-label="Close"
          >
            <X size={20} />
          </button>
        </div>
        <div className="px-6 py-5 overflow-y-auto">
          <pre className="whitespace-pre-wrap text-sm text-slate-600 font-sans leading-relaxed">
            {content}
          </pre>
        </div>
      </div>
    </div>
  )
}

export default function Footer({ user, onRequestAuth, toast }) {
  const [modal, setModal] = useState(null)

  return (
    <footer className="border-t border-slate-200 bg-white">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 py-8">
        <div className="flex flex-col items-center gap-4">
          <div className="flex items-start gap-2 max-w-3xl text-center">
            <AlertTriangle size={16} className="text-amber-500 mt-0.5 flex-shrink-0" />
            <p className="text-xs text-slate-500 leading-relaxed">
              Snap-to-Quiz uses artificial intelligence to generate study materials for
              supplemental learning. Answers are provided 'as-is' and may contain
              inaccuracies. Verify critical facts.
            </p>
          </div>

          <div className="flex items-center gap-4 flex-wrap justify-center">
            <button
              onClick={() => setModal('terms')}
              className="flex items-center gap-1.5 text-sm text-slate-600 hover:text-blue-600 transition-colors"
            >
              <FileText size={14} />
              Terms of Service
            </button>
            <button
              onClick={() => setModal('privacy')}
              className="flex items-center gap-1.5 text-sm text-slate-600 hover:text-blue-600 transition-colors"
            >
              <Shield size={14} />
              Privacy Policy
            </button>
          </div>

          <p className="text-xs text-slate-400">
            &copy; {new Date().getFullYear()} Snap-to-Quiz. All rights reserved.
          </p>
        </div>
      </div>

      {modal === 'terms' && (
        <LegalModal
          title="Terms of Service"
          content={TERMS_TEXT}
          onClose={() => setModal(null)}
        />
      )}
      {modal === 'privacy' && (
        <LegalModal
          title="Privacy Policy"
          content={PRIVACY_TEXT}
          onClose={() => setModal(null)}
        />
      )}
      <FeedbackButton user={user} onRequestAuth={onRequestAuth} toast={toast} />
    </footer>
  )
}
